In [52]:
import pandas as pd 
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv(r"C:\Users\CR\Downloads\sleeptime_prediction_dataset.csv")

In [74]:
df = df.dropna()
df.head()

WorkoutTime  ReadingTime  PhoneTime  WorkHours  CaffeineIntake  \
0         1.12         0.52       3.29       7.89          216.08   
1         2.85         0.49       4.22       5.03          206.18   
2         2.20         1.81       4.04       9.23           28.73   
3         1.80         0.50       1.62       7.68          276.77   
4         0.47         0.54       1.60       4.94          170.54   

   RelaxationTime  SleepTime  
0            0.75       3.45  
1            0.67       4.88  
2            0.35       3.61  
3            1.21       4.94  
4            0.95       5.50

In [75]:
df.describe()

WorkoutTime  ReadingTime    PhoneTime    WorkHours  CaffeineIntake  \
count  2000.000000  2000.000000  2000.000000  2000.000000     2000.000000   
mean      1.495915     0.992785     2.985195     6.926945      147.493780   
std       0.876639     0.577303     1.151776     1.723843       84.651139   
min       0.010000     0.000000     1.000000     4.000000        0.020000   
25%       0.710000     0.500000     1.990000     5.440000       75.980000   
50%       1.520000     0.990000     2.965000     6.910000      146.010000   
75%       2.250000     1.500000     3.960000     8.422500      218.902500   
max       3.000000     2.000000     5.000000    10.000000      299.850000   

       RelaxationTime    SleepTime  
count     2000.000000  2000.000000  
mean         1.010955     4.884375  
std          0.582619     2.028892  
min          0.000000     0.150000  
25%          0.510000     3.840000  
50%          1.010000     4.600000  
75%          1.530000     5.470000  
max          2.000000    19.810000

In [76]:
lr = LinearRegression()

In [77]:
X = np.array(df[["WorkoutTime","ReadingTime","PhoneTime","WorkHours"]])

Y = df["SleepTime"]
print(X)
print(Y)

[[1.12 0.52 3.29 7.89]
 [2.85 0.49 4.22 5.03]
 [2.2  1.81 4.04 9.23]
 ...
 [0.21 0.79 4.06 6.73]
 [0.17 1.06 2.94 9.45]
 [0.85 0.32 1.6  4.63]]
0       3.45
1       4.88
2       3.61
3       4.94
4       5.50
        ... 
1995    4.24
1996    5.89
1997    3.00
1998    3.53
1999    5.83
Name: SleepTime, Length: 2000, dtype: float64


In [83]:
xtrain,xtest,ytrain,ytest = train_test_split(X,Y)

In [84]:
print(xtrain.shape)
print(ytrain.shape)



(1500, 4)
(1500,)


In [85]:
lr.fit(xtrain,ytrain)

LinearRegression()